### PR TITLE
Add option to display date and time of last update

### PR DESCRIPTION
**Pull request by abhijoshi2k**
Thank you for contributing! Please check the following things before submiting your PR:

Required:
- [x] I have read and followed the [contributing guidelines](https://github.com/Readme-Workflows/recent-activity/blob/main/.github/CONTRIBUTING.md)

If necessary:
- [x] I have updated the README and documentation.
- [ ] I have updated the ChangeLog with the changes I have made.

## Description

Added support for Date of update
Markdown file comments changed as follows:
`<!--START_SECTION:activity-->` changes to `<!--RECENT_ACTIVITY:start-->`
`<!--END_SECTION:activity-->` changes to `<!--RECENT_ACTIVITY:start-->`

For adding Date, add this to your markdown file:
`<!--RECENT_ACTIVITY:last_update-->`

For adding timezone and date format, add the following parameters to `.yml` file:
`TIMEZONE_OFFSET`
```
    description: "Timezone in which time is to be displayed"
    default: "0"
    required: false
```

`DATE_STRING`
```
    description: "String to be printed while printing updation date"
    default: "Last Updated: {DATE}"
    required: false
```

`DATE_FORMAT`
```
    description: "Format of how last updation time to be printed"
    default: "dddd, mmmm dS, yyyy, h:MM:ss TT"
    required: false
```
For date formats, refer : https://www.npmjs.com/package/dateformat

Closes #

---------------------------------------------------------------------

**Note:** we will close your PR without comment if you do not check the required boxes above and provide ALL requested information.

### CODE REVIEW

**Comment by abhijoshi2k** [comment]
@PuneetGopinath @Andre601 Please check.

**Comment by PuneetGopinath** [comment]
0 will make the timezone to UTC right

**Comment by PuneetGopinath** [comment]
@abhijoshi2k You have to review #39 before this pr can be merged

**Review by Andre601 — APPROVED** [review]
Works perfectly.
image

**Comment by PuneetGopinath** [comment]
Cool.

**Comment by PuneetGopinath** [comment]
> `0` will set the timezone to UTC right

@abhijoshi2k ?

**Comment by Andre601** [comment]
> > `0` will set the timezone to UTC right
> 
> @abhijoshi2k ?

It's just the offset from GMT which is UTC, so yes. I for example had `+2:00` set on the above date

**Review by PuneetGopinath — APPROVED** [review]

**Comment by PuneetGopinath** [comment]
> It's just the offset from GMT which is UTC, so yes. I for example had `+2:00` set on the above date

Thanks, do you think #39 is ready for review

**Comment by Andre601** [comment]
Once this is merged will I add some info to the Release to inform about breaking changes.

**Comment by abhijoshi2k** [comment]
> `0` will set the timezone to UTC right

Yes

**Comment by abhijoshi2k** [comment]
> @abhijoshi2k You have to review #39 before this pr can be merged

I shall do it. There are some changes I have to make here.
Will fix 1 bug and then review #39

**Comment by PuneetGopinath** [comment]
I minute plz don't merge

**Comment by abhijoshi2k** [comment]
> 1 minute plz don't merge

I just pushed. 1 sec before your change

**Comment by abhijoshi2k** [comment]
> > 1 minute plz don't merge
> 
> I just pushed. 1 sec before your comment

**Comment by PuneetGopinath** [comment]
Ok

**Comment by Andre601** [comment]
> > 1 minute plz don't merge
> 
> I just pushed. 1 sec before your change

Just add the `Status: Ready` label once your PR is ready for merge.

**Comment by abhijoshi2k** [comment]
> > 1 minute plz don't merge
> 
> Just add the `Status: Ready` label once your PR is ready for merge.

It's ready.

**Comment by PuneetGopinath** [comment]
The exact package-lock.json change was the thing I wanted to do.

**Comment by abhijoshi2k** [comment]
> The exact package-lock.json change was the thing I wanted to do.

Okay. Now I think we can merge

**Comment by PuneetGopinath** [comment]
This time I by mistake forgot to squash and merge 🤣

**Comment by abhijoshi2k** [comment]
> This time I by mistake forgot to squash and merge 🤣

It's fine...

**Pull request merged**
