### PR TITLE
Users can change comment text

### PR DESCRIPTION
**Pull request by PuneetGopinath**
Thank you for contributing! Please check the following things before submiting your PR:

Required:
- [x] I have read and followed the [contributing guidelines](https://github.com/Readme-Workflows/recent-activity/blob/main/.github/CONTRIBUTING.md)

If necessary:
- [ ] I have updated the README and documentation.
- [ ] I have updated the ChangeLog with the changes I have made.

> Users can change comment text

Closes #

---------------------------------------------------------------------

**Note:** we will close your PR without comment if you do not check the required boxes above and provide ALL requested information.

### CODE REVIEW

**Comment by abhijoshi2k** [comment]
You will have to use replaceAll(). I'm working on it on other branch.

**Comment by PuneetGopinath** [comment]
Ohh, ok...

**Comment by abhijoshi2k** [comment]
Can you work on #4 .
I'm already working on this one.

**Comment by PuneetGopinath** [comment]
ok

**Pull request closed without merging**
