### PR TITLE
fix: # of activity lines changes according to max_lines property

### LINKED ISSUE #159: Bug report: # of activity lines remains the same after I change `max_lines` property
### Checks

- [X] I use a [supported version](https://github.com/Readme-Workflows/recent-activity/blob/main/SUPPORTED_VERSIONS.md) of Recent Activity.
- [X] I [searched the issues page](https://github.com/Readme-Workflows/recent-activity/issues?q=is%3Aissue) for already existing bug reports.

### Description

The number of activity lines remains the same after I change `max_lines` property

### Steps to reproduce

1. Run workflow with default settings.
2. Change the `max_lines` property value inside `.github/recent-activity.config.yml` into 8.
3. Re-run the workflow.

### Configuration

```yaml
name: Recent activity

on:
  schedule:
    - cron: '*/30 * * * *' # Update every 30 minutes
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update this repo's README with recent activity

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: Readme-Workflows/recent-activity@v2.3.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

---

settings:
  username: "jooncco"
  commit_msg: "⚡ Update README with the recent activity"
  max_lines: 8
  readme_file: "./README.md"
  disabled_events:
    - "comments"
  url_text: "{REPO}{ID}"
  date:
    timezone: "GMT+09:00"
    text: "Last Updated: {DATE}"
    format: "dddd, mmmm dS, yyyy, h:MM:ss TT"
  commit_name: "readme-bot"
  commit_email: "41898282+github-actions[bot]@users.noreply.github.com"
messages:
  comments: "💬 Commented on {ID} in {REPO}"
  issue_opened: "❗️ Opened issue {ID} in {REPO}"
  issue_closed: "✔️ Closed issue {ID} in {REPO}"
  pr_opened: "💪 Opened PR {ID} in {REPO}"
  pr_closed: "❌ Closed PR {ID} in {REPO}"
  pr_merged: "🎉 Merged PR {ID} in {REPO}"
  create_repo: "📔 Created new repository {REPO}"
  fork_repo: "🔱 Forked {FORK} from {REPO}"
  wiki_create: "📖 Created new wiki page {WIKI} in {REPO}"
  added_member: "🤝 Became collaborator on {REPO}"
  changes_approved: "👍 Approved {ID} in {REPO}"
  changes_requested: "🔴 Requested changes in {ID} in {REPO}"
  new_release: "✌️ Released {ID} in {REPO}"
  new_star: "⭐ Starred {REPO}"
```

### Expected behaviour

newest 8 activity lines are showing

### Actual behaviour

newest 5 activity lines are showing

### Failed runs

_No response_

### PR DESCRIPTION
**Pull request by jooncco**
## Checks

I have...

- [x] read and understood the [Contributing Guidelines][contributing]
- [x] Updated any nessecary files such as the README.md and/or CHANGELOG.md.

## Type of Pull request

- [ ] **Minor Change**  
  This Pull request doesn't break existing configuration.
- [x] **Major Change**  
  This Pull request will break existing configuration.
- [ ] **Bug fix**  
  This Pull request will fix a (critical) bug.
- [ ] **Documentation**  
  This Pull request only changes documentation (README.md, CHANGELOG.md, etc.)
- [ ] **Other:** `__________` 

## Description

This pull request fixes #159.
The number of activity lines will change according to `max_lines` property every time workflow runs.

Closes #159 

[contributing]: https://github.com/Readme-Workflows/.github/blob/main/.github/CONTRIBUTING.md

### CODE REVIEW

**Comment by abhijoshi2k** [comment]
This cannot be done because when user changes `max-lines` parameter, this might result into content lines being overwritten.
The simple solution here is to reset the workflow manually by removing the recent activity lines (run it as if running for first time)

**Comment by jooncco** [comment]
> This cannot be done because when user changes `max-lines` parameter, this might result into content lines being overwritten. The simple solution here is to reset the workflow manually by removing the recent activity lines (run it as if running for first time)

Thanks for the reply, @abhijoshi2k.
My changes doesn't affect other contents in README.md.
```javascript
readmeContent.splice(startIdx, endIdx-startIdx);
```
This line limits the deletion into only `[startIdx, endIdx)`.

**Comment by jooncco** [comment]
And thanks for the simple solution.
I actually was aware of that, but wanted to suggest this kind of feature.

**Comment by abhijoshi2k** [comment]
I'll test it once and get back to you. I'm a bit occupied currently. Give me some time.

**Comment by abhijoshi2k** [comment]
@jooncco Thanks for the PR. I just tested your edited code. It works as expected. So I think this is ready to be merged.
@PuneetGopinath I am approving this. Please check and merge.

**Review by abhijoshi2k — APPROVED** [review]

**Review by PuneetGopinath — APPROVED** [review]

**Comment by jooncco** [comment]
appreciate it :)

**Comment by kaustav202** [comment]
@PuneetGopinath  @abhijoshi2k  @jooncco  I am still facing the issue . I've tried removing the recent activity comment to no avail. It always limits to 5 activities only. Kindly let me know if there's any workaround to it. Thank you.

**Comment by Andre601** [comment]
Did you actually update your settings?
Also, please open a discussion for support.

**Pull request merged**
