### PR TITLE
Easily get the URL of the issue/comment/pull_request

### PR DESCRIPTION
**Pull request by PuneetGopinath**
Thank you for contributing! Please check the following things before submiting your PR:

Required:
- [x] I have read and followed the [contributing guidelines](https://github.com/Readme-Workflows/recent-activity/blob/main/.github/CONTRIBUTING.md)

If necessary:
- [ ] I have updated the README and documentation.
- [ ] I have updated the ChangeLog with the changes I have made.

## Description

For example, to get issue url you currently use `${urlPrefix}/${item.repo.name}/issues/${item.payload.issue.number}` to get the URL of the issue or comment, instead you could easily use `${item.payload.issue.html_url}` for issue url, `${item.payload.pull_request.html_url}` for pull request url and `${item.payload.comment.html_url}` for issue comment url.

This pr, will also fulfil a feature request, requested somewhere else: https://github.com/jamesgeorge007/github-activity-readme/issues/54

Closes #

---------------------------------------------------------------------

**Note:** we will close your PR without comment if you do not check the required boxes above and provide ALL requested information.

### CODE REVIEW

**Review by Andre601 — APPROVED** [review]

**Comment by PuneetGopinath** [comment]
Note: this pr also changes `run-build.yml` workflow, it uses npm co, but npm install will make it work better.

**Comment by Andre601** [comment]
Will this be a new release or will there be other changes before a new release?

**Comment by PuneetGopinath** [comment]
Yes, there should be a new release, @Andre601 Is the issue you opened a bug report or feature request actually

**Comment by Andre601** [comment]
> Yes, there should be a new release, @Andre601 Is the issue you opened a bug report or feature request actually, in [jamesgeorge007/github-activity-readme#54](https://github.com/jamesgeorge007/github-activity-readme/issues/54)

Feature request

**Comment by PuneetGopinath** [comment]
Ok, then next version is `v1.4.0`

**Comment by PuneetGopinath** [comment]
Releasing a new version should be v1.4.0 because, a new feature added means a new minor version, as we are following semver.org

**Comment by PuneetGopinath** [comment]
@abhijoshi2k Just waiting for your review

**Comment by abhijoshi2k** [comment]
> Note: this pr also changes `run-build.yml` workflow, it uses `npm ci`, but `npm install` will make it work better.

`npm ci` is faster and does not change the lock file according to docs. Then why go for `npm install` ?

**Comment by PuneetGopinath** [comment]
Ok, then as you say will use npm ci

**Review by abhijoshi2k — APPROVED** [review]

**Comment by abhijoshi2k** [comment]
@PuneetGopinath squash and merge this time right?

**Comment by PuneetGopinath** [comment]
Sorry, I did it

**Pull request merged**
