### PR TITLE
Prepare Changelog

### PR DESCRIPTION
**Pull request by Andre601**
## Checks

I have...

- [x] read and understood the [Contributing Guidelines][contributing]
- [x] Updated any nessecary files such as the README.md and/or CHANGELOG.md.

## Type of Pull request

- [ ] **Minor Change**  
  This Pull request doesn't break existing configuration.
- [ ] **Major Change**  
  This Pull request will break existing configuration.
- [ ] **Bug fix**  
  This Pull request will fix a (critical) bug.
- [x] **Documentation**  
  This Pull request only changes documentation (README.md, CHANGELOG.md, etc.)
- [ ] **Other:** `__________` 

## Description

Updated Changelog.

Closes #

[contributing]: https://github.com/Readme-Workflows/recent-activity/blob/main/.github/CONTRIBUTING.md

### CODE REVIEW

**Comment by PuneetGopinath** [comment]
@Andre601 I think this PR is ready for review

**Review by PuneetGopinath — APPROVED** [review]

**Comment by abhijoshi2k** [comment]
> @Andre601 I think this PR is ready for review

No it's not. We still have some events to add!

**Comment by PuneetGopinath** [comment]
@Andre601 Can you update the events and set this pr to "Ready for review"

**Review by abhijoshi2k — APPROVED** [review]
Looks perfect

**Pull request merged**
