### PR TITLE
Shift to glitch

### PR DESCRIPTION
**Pull request by abhijoshi2k**
## Checks

I have...

- [x] read and understood the [Contributing Guidelines][contributing]
- [ ] Updated any nessecary files such as the README.md and/or CHANGELOG.md.

## Type of Pull request

- [x] **Minor Change**  
  This Pull request doesn't break existing configuration.
- [ ] **Major Change**  
  This Pull request will break existing configuration.
- [ ] **Bug fix**  
  This Pull request will fix a (critical) bug.
- [ ] **Documentation**  
  This Pull request only changes documentation (README.md, CHANGELOG.md, etc.)
- [ ] **Other:** `__________` 

## Description

Shifted from Heroku to Glitch in order to have a single domain. Heroku links will stop working in coming days.

Closes #

[contributing]: https://github.com/Readme-Workflows/recent-activity/blob/main/.github/CONTRIBUTING.md

### CODE REVIEW

**Review by PuneetGopinath — APPROVED** [review]

**Comment by PuneetGopinath** [comment]
Andre, can you update the changelog

**Comment by abhijoshi2k** [comment]
There's no need to update readme here. Update changelog only. We need to release ASAP

**Comment by PuneetGopinath** [comment]
> There's no need to update readme here. Update changelog only. We need to release ASAP

I didn't say to update readme bro

**Comment by abhijoshi2k** [comment]
> > There's no need to update readme here. Update changelog only. We need to release ASAP
> 
> I didn't say to update readme bro

I'm just mentioning for information.

**Pull request merged**
