### PR TITLE
Improve release-drafter

### PR DESCRIPTION
**Pull request by Andre601**
Thank you for contributing! Please check the following things before submiting your PR:

Required:
- [x] I have read and followed the [contributing guidelines](https://github.com/Readme-Workflows/recent-activity/blob/main/.github/CONTRIBUTING.md)

If necessary:
- [ ] I have updated the README and documentation.
- [ ] I have updated the ChangeLog with the changes I have made.

> Improves the displayed title for the categories, changing them to `### $TITLE`
>
> **Example:**
> - *Before*
>   ## Release notes
>   
>   ## 📖 Docs
>   - Update README.md @PuneetGopinath (#34)
> - *After*
>   ## Release notes
>   
>   ### 📖 Docs
>   - Update README.md @PuneetGopinath (#34)

Closes #

---------------------------------------------------------------------

**Note:** we will close your PR without comment if you do not check the required boxes above and provide ALL requested information.

### CODE REVIEW

**Review by abhijoshi2k — APPROVED** [review]
Looks good

**Comment by Andre601** [comment]
While we're at it, would I like to ask, if we perhaps should ignore PRs targeting GitHub Action workflows, since people don't really need this info on changelog, right?

**Comment by abhijoshi2k** [comment]
> While we're at it, would I like to ask, if we perhaps should ignore PRs targeting GitHub Action workflows, since people don't really need this info on changelog, right?

I too really doubt if people read it. We should focus more on workflow functionality is my opinion.

**Comment by Andre601** [comment]
I changed it, so that PRs targeting github action workflows are ignored.

**Review by PuneetGopinath — APPROVED** [review]

**Comment by Andre601** [comment]
Now we have to wait for GitHub Actions to be fixed for this to update the release xD

**Comment by PuneetGopinath** [comment]
> Now we have to wait for GitHub Actions to be fixed for this to update the release xD

What to be fixed

**Comment by Andre601** [comment]
https://www.githubstatus.com/incidents/zbpwygxwb3gw

**Comment by PuneetGopinath** [comment]
Means currently GitHub actions will not be available.

**Comment by Andre601** [comment]
> Means currently GitHub actions is not be available.

Yes. Currently scheduled actions are in "in queue" mode indefinitely (perhaps even time out after a long time?) until GitHub fixed the issue.

You can see this happening in the Actions tab of this repo:
image

**Comment by PuneetGopinath** [comment]
Yes, do you know what problems

**Comment by Andre601** [comment]
Nah. We just have to wait for GitHub to fix this.

**Comment by PuneetGopinath** [comment]
You are too fast, I think as soon as you saw in Actions tab, I think you rushed to GitHub status, right?

**Comment by Andre601** [comment]
I already knew this for some time now when I was working on one of my projects

**Comment by PuneetGopinath** [comment]
Ok.

**Pull request merged**
