### PR TITLE
Prepare Changelog and wiki for v2.3.1 release

### PR DESCRIPTION
**Pull request by Andre601**
## Checks

I have...

- [x] read and understood the [Contributing Guidelines][contributing]
- [x] Updated any nessecary files such as the README.md and/or CHANGELOG.md.

## Type of Pull request

- [ ] **Minor Change**  
  This Pull request doesn't break existing configuration.
- [ ] **Major Change**  
  This Pull request will break existing configuration.
- [ ] **Bug fix**  
  This Pull request will fix a (critical) bug.
- [x] **Documentation**  
  This Pull request only changes documentation (README.md, CHANGELOG.md, etc.)
- [ ] **Other:** `__________` 

## Description

Updates CHANGELOG.md and the Configuration page of the wiki with the latest changes from #90 

Closes #

[contributing]: https://github.com/Readme-Workflows/.github/blob/main/.github/CONTRIBUTING.md

### CODE REVIEW

**Comment by abhijoshi2k** [comment]
Andre601, as discussed, I'm making 2 test reviews to make sure #90 is working well. Sorry for notifications.

**Review by abhijoshi2k — CHANGES_REQUESTED** [review]
This is a test review

**Review by abhijoshi2k — CHANGES_REQUESTED** [review]
Test review

**Review by abhijoshi2k — APPROVED** [review]

**Comment by PuneetGopinath** [comment]
Sorry, I didn't checkout because I had turned off notifications 🙃

**Pull request merged**
