### PR TITLE
Update

### PR DESCRIPTION
**Pull request by PuneetGopinath**
Add config.yml, dependabot.yml, ChangeLog.md, SUPPORT.md, CONTRIBUTING.md, PULL_REQUEST_TEMPLATE.md, release-notes.yml

### CODE REVIEW

**Comment by PuneetGopinath** [comment]
I understood now, The failing workflow is not an issue, see https://github.com/release-drafter/release-drafter/issues/835#issuecomment-815297195

**Comment by PuneetGopinath** [comment]
@abhijoshi2k plz review

**Comment by abhijoshi2k** [comment]
@PuneetGopinath Any idea why check failed?

**Review by abhijoshi2k — APPROVED** [review]
I think it's fine if failing workflow isn't an issue.

**Comment by PuneetGopinath** [comment]
> @PuneetGopinath Any idea why check failed?
> It failed on latest commit. It was fine before that

It failed on the latest commit because the release-notes workflow run on pr, see that I commented out push in the workflow. Anyway the only reason I commented is because it doesn't does anything while pushing because their are no labels when we add a commit😂.
Did you see https://github.com/release-drafter/release-drafter/issues/835#issuecomment-815297195

**Comment by abhijoshi2k** [comment]
Yeah! so that means it'll work on default branch right?

**Comment by PuneetGopinath** [comment]
Yes

**Comment by PuneetGopinath** [comment]
Will I merge this pr?

**Review by abhijoshi2k — APPROVED** [review]
I think we should merge. Is there anything else you are planning to add to this?

**Comment by PuneetGopinath** [comment]
Nop, you can merge

**Comment by PuneetGopinath** [comment]
Haha, welcome bot commented, you can see this sample message by welcome bot👆

**Comment by PuneetGopinath** [comment]
Note: I forgot to saw that I granted welcome bot access in this org.

**Comment by abhijoshi2k** [comment]
It looks good.

**Comment by PuneetGopinath** [comment]
See another pr by dependabot

**Pull request merged**
