### PR TITLE
Issue#5

### PR DESCRIPTION
**Pull request by abhijoshi2k**
Thank you for contributing! Please check the following things before submiting your PR:

Required:
- [x] I have read and followed the [contributing guidelines](https://github.com/Readme-Workflows/recent-activity/blob/main/.github/CONTRIBUTING.md)

If necessary:
- [ ] I have updated the README and documentation.
- [x] I have updated the ChangeLog with the changes I have made.

> Replace this line with a short description about the changes you have made in this PR e.g. Corrected spelling mistakes in docs

---------------------------------------------------------------------

**Note:** we will close your PR without comment if you do not check the required boxes above and provide ALL requested information.

### CODE REVIEW

**Comment by abhijoshi2k** [comment]
@PuneetGopinath I still have to add other things. Will request review once it's done.

**Comment by PuneetGopinath** [comment]
Yes, No probs

**Comment by abhijoshi2k** [comment]
@PuneetGopinath I've added the required customizations. But we need to check once by merging.
Once we have tested everything, we will add it to readme.

**Comment by PuneetGopinath** [comment]
> @PuneetGopinath I've added the required customizations. But we need to check once by merging.
> Once we have tested everything, we will add it to readme.

Sure

**Comment by abhijoshi2k** [comment]
Please review and merge. Let me know if any changes are required.

**Comment by PuneetGopinath** [comment]
I am facing problem installing prettier, Can you run build?

**Comment by abhijoshi2k** [comment]
> Can you run build?

Done

**Comment by PuneetGopinath** [comment]
Now last we have to add it to readme and changelog

**Comment by PuneetGopinath** [comment]
I will add to changelog, you can add to readme

**Comment by abhijoshi2k** [comment]
> Now last we have to add it to readme and changelog

We need to test on our own repos first.

**Comment by abhijoshi2k** [comment]
> > Now last we have to add it to readme and changelog
> 
> We need to test on our own repos first.

For that we must merge. Should we?

**Comment by PuneetGopinath** [comment]
Yes, after merging branch main, Can you release `v1.2.0-alpha`?

**Comment by PuneetGopinath** [comment]
Yes, we have to merge branch main
But how can we test without merging this pr?

**Comment by abhijoshi2k** [comment]
> Yes, we have to merge branch main
> But how can we test without merging this pr?

We can change branch in our workflow. Currently it is main. We can change it to issue#5

**Comment by PuneetGopinath** [comment]
Ohh yes

**Comment by PuneetGopinath** [comment]
Ohh yes
Have to release new version?
I also have doubt whether we are following semantic version?

**Comment by PuneetGopinath** [comment]
No need to release new version right?

**Comment by abhijoshi2k** [comment]
> No need to release new version right?

Nope. We will release after testing

**Comment by PuneetGopinath** [comment]
I tried using issue#5 branch, but because of # it failed, So I used test branch

**Comment by abhijoshi2k** [comment]
> I tried using issue#5 branch, but because of # it failed, So I used test branch (test branch also failed, should we change default ranch)

It worked for me.

**Comment by abhijoshi2k** [comment]
https://github.com/abhijoshi2k/abhijoshi2k/actions/runs/824759624
check this

**Comment by PuneetGopinath** [comment]
> > I tried using issue#5 branch, but because of # it failed, So I used test branch (test branch also failed, should we change default ranch)
> 
> It worked for me.

I made I mistake, anyway if it works, we can update readme, pull main and merge this pr

**Review by PuneetGopinath — APPROVED** [review]

**Comment by PuneetGopinath** [comment]
Don't release after merging this pr, #4 has to be completed

**Comment by abhijoshi2k** [comment]
> Don't release after merging this pr, #4 has to be completed

Okay. I'll update readme and merge. Will wait for release till #4 is completed.

**Comment by PuneetGopinath** [comment]
Add 
```
| `COMMENTS_ACTIVITY` | How the comments activity should be printed.                   | 🗣 Commented on {ID} in {REPO}            |
| `ISSUE_OPENED`      | How the 'issue opened' activity should be printed.             | ❗️ Opened issue {ID} in {REPO}             |
| `ISSUE_CLOSED`      | How the 'issue closed' activity should be printed.             | ❗️ Closed issue {ID} in {REPO}             |
| `PR_OPENED`         | How the 'pull request opened' activity should be printed.      | 💪 Opened PR {ID} in {REPO}              |
| `PR_CLOSED`         | How the 'pull request closed' activity should be printed.      | ❌ Closed PR {ID} in {REPO}              |
| `PR_MERGED`         | How the 'pull request merged' activity should be printed.      | 🎉 Merged PR {ID} in {REPO}              |
```

in readme

Preview:
| Option              | Description                                                    | Default                                   |
| ------------------- | -------------------------------------------------------------- | ----------------------------------------- |
| `COMMENTS_ACTIVITY` | How the comments activity should be printed.                   | 🗣 Commented on {ID} in {REPO}            |
| `ISSUE_OPENED`      | How the 'issue opened' activity should be printed.             | ❗️ Opened issue {ID} in {REPO}             |
| `ISSUE_CLOSED`      | How the 'issue closed' activity should be printed.             | ❗️ Closed issue {ID} in {REPO}             |
| `PR_OPENED`         | How the 'pull request opened' activity should be printed.      | 💪 Opened PR {ID} in {REPO}              |
| `PR_CLOSED`         | How the 'pull request closed' activity should be printed.      | ❌ Closed PR {ID} in {REPO}              |
| `PR_MERGED`         | How the 'pull request merged' activity should be printed.      | 🎉 Merged PR {ID} in {REPO}              |

**Comment by Andre601** [comment]
What about a `{URL}` option that would resolve into a URL?
Or do both `{ID}` and `{REPO}` resolve into linking to the issue/PR and Repo respectively? Kind of limiting if you ask me.

**Comment by abhijoshi2k** [comment]
> What about a `{URL}` option that would resolve into a URL?
> Or do both `{ID}` and `{REPO}` resolve into linking to the issue/PR and Repo respectively? Kind of limiting if you ask me.

{ID} and {REPO} both resolve into inking to the issue/PR and Repo respectively.
So clicking on those will take you to respective issue/PR and repository.

I don't understand what would be the use of {URL}

**Comment by Andre601** [comment]
> > What about a `{URL}` option that would resolve into a URL?
> > Or do both `{ID}` and `{REPO}` resolve into linking to the issue/PR and Repo respectively? Kind of limiting if you ask me.
> 
> {ID} and {REPO} both resolve into inking to the issue/PR and Repo respectively.
> So clicking on those will take you to respective issue/PR and repository.
> 
> I don't understand what would be the use of {URL}

Was shown in my issue.
Essentially something like ``[`{REPO}#{ID}`]({URL})`` which f.e. resolved into [`Readme-Workflows/recent-activity#11`](https://github.com/Readme-Workflows/recent-activity/pull/11) would be possible.

**Comment by abhijoshi2k** [comment]
@Andre601 Can you give me an example output having {URL}?

**Comment by Andre601** [comment]
> @Andre601 Can you give me an example output having {URL}?

`{URL}` would essentially do what `{ID}` and `{REPO}` do right now, which is directly linking to the issue, comment, PR

**Comment by abhijoshi2k** [comment]
@Andre601 That would be raw format. Such formats are difficult for users with less knowledge of markdown.
We can add it though. Then if the {URL} is mentioned, it'll be treated as raw markdown and workflow will just replace text as it is and add the issue/pr URL to it.
But if user formats f.e. `COMMENTS_ACTIVITY` in improper way, output will be some very weird string.
I don't know if I'm able to explain my concern properly.
I just want to say that it will be difficult for user to format this.

We can instead add 1 more parameter:
`URL_FORMAT` --> Will contain how {URL} will be replaced f.e. `{REPO}{ID}` will give same result as you earlier mentioned.

So user will only have to add `{URL}` and not `[`{REPO}#{ID}`]({URL})`

**Comment by Andre601** [comment]
> We can instead add 1 more parameter:
> `URL_FORMAT` --> Will contain how {URL} will be replaced f.e. `{REPO}{ID}` will give same result as you earlier mentioned.
> 
> So user will only have to add `{URL}` and not `[{REPO}#{ID}]({URL})`

That would be an idea.

**Comment by abhijoshi2k** [comment]
> > We can instead add 1 more parameter:
> > `URL_FORMAT` --> Will contain how {URL} will be replaced f.e. `{REPO}{ID}` will give same result as you earlier mentioned.
> > So user will only have to add `{URL}` and not `[{REPO}#{ID}]({URL})`
> 
> That would be an idea.

Okay. I'll work on it.

**Pull request merged**
