### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by Andre601**
Thank you for contributing! Please check the following things before submiting your PR:

Required:
- [x] I have read and followed the [contributing guidelines](https://github.com/Readme-Workflows/recent-activity/blob/main/.github/CONTRIBUTING.md)

If necessary:
- [x] I have updated the README and documentation.
- [ ] I have updated the ChangeLog with the changes I have made.

## Description

Adds a section about the different Comment options you can use in markdown files.

Closes #

---------------------------------------------------------------------

**Note:** we will close your PR without comment if you do not check the required boxes above and provide ALL requested information.

### CODE REVIEW

**Review by PuneetGopinath — APPROVED** [review]

**Comment by PuneetGopinath** [comment]
@Andre601 Is this pr ready for review?

**Comment by PuneetGopinath** [comment]
@abhijoshi2k Please review

**Comment by PuneetGopinath** [comment]
@abhijoshi2k Can you merge branch updation-time into this branch

**Comment by Andre601** [comment]
The changelog is handled in #41 :)

**Comment by abhijoshi2k** [comment]
@Andre601 @PuneetGopinath  
Can we remove `RECENT_ACTIVITY:end` and `RECENT_ACTIVITY:last_update_end` from the `Options` table?
It might confuse the users. Also, users don't have to add it themselves. Workflow will take care of it.
I can see that you clearly mentioned this fact. But I still feel we should remove those rows.

**Comment by PuneetGopinath** [comment]
> The changelog is handled in #41 :)

Ok

**Comment by PuneetGopinath** [comment]
> @Andre601 @PuneetGopinath
> Can we remove `RECENT_ACTIVITY:end` and `RECENT_ACTIVITY:last_update_end` from the `Options` table?
> It might confuse the users. Also, users don't have to add it themselves. Workflow will take care of it.
> I can see that you clearly mentioned this fact. But I still feel we should remove those rows.

Oh yes, you are right
@Andre601 Can you remove I am little busy.

**Comment by abhijoshi2k** [comment]
@Andre601 Can we add a Wiki to show supported placeholders in date format?

Supported formats: https://www.npmjs.com/package/dateformat

We support the `masked options` as well as `named formats`

**Comment by abhijoshi2k** [comment]
> @Andre601 Can we add a Wiki to show supported placeholders in date format?
> 
> Supported formats: https://www.npmjs.com/package/dateformat
> 
> We support the `masked options` as well as `named formats`

You can get raw README of that package on this repo: https://github.com/felixge/node-dateformat

**Comment by Andre601** [comment]
> @Andre601 Can we add a Wiki to show supported placeholders in date format?
> 
> Supported formats: https://www.npmjs.com/package/dateformat
> 
> We support the `masked options` as well as `named formats`

Added [an example](https://github.com/Readme-Workflows/recent-activity/wiki/Examples#different-date-and-time-format)

**Comment by abhijoshi2k** [comment]
I was thinking we can add something like this:
image

**Comment by abhijoshi2k** [comment]
> I was thinking we can add something like this:

It's available here : https://github.com/felixge/node-dateformat

**Comment by Andre601** [comment]
Not worth to add this info imo if it already exists. I already link to the npm package and that should be enough.

You should better try to fix the conflicts in this PR because I won't touch JS stuff here.

**Comment by PuneetGopinath** [comment]
I think we can add

**Comment by abhijoshi2k** [comment]
> Not worth to add this info imo if it already exists. I already link to the npm package and that should be enough.
> 
> You should better try to fix the conflicts in this PR because I won't touch JS stuff here.

Okay. I'll resolve the conflicts.
Should I merge after that?

**Review by abhijoshi2k — APPROVED** [review]

**Comment by Andre601** [comment]
> > Not worth to add this info imo if it already exists. I already link to the npm package and that should be enough.
> > You should better try to fix the conflicts in this PR because I won't touch JS stuff here.
> 
> Okay. I'll resolve the conflicts.
> Should I merge after that?

Yes

**Comment by PuneetGopinath** [comment]
> > Not worth to add this info imo if it already exists. I already link to the npm package and that should be enough.
> > You should better try to fix the conflicts in this PR because I won't touch JS stuff here.
> 
> Okay. I'll resolve the conflicts.
> Should I merge after that?

No, after resolving conflicts you should pull branch updation-time

**Comment by PuneetGopinath** [comment]
@abhijoshi2k Better delete node_modules folder.
I messaged you in discord that "Yes, I afterwards saw in GitHub docs that if you use ncc then you should remove node_modules folder.
We are using @vercel/ncc npm package"

**Comment by PuneetGopinath** [comment]
Better I itself will delete, because you started working and you are not going to see my comment

**Comment by abhijoshi2k** [comment]
> Better I itself will delete, because you started working and you are not going to see my comment

The bot added it back

**Comment by PuneetGopinath** [comment]
> > Better I itself will delete, because you started working and you are not going to see my comment
> 
> The bot added it back

Yeah, I see I will force push

**Comment by abhijoshi2k** [comment]
> > > Better I itself will delete, because you started working and you are not going to see my comment
> > 
> > 
> > The bot added it back
> 
> Yeah, I see I will force push

I think it's fine if we have node_modules. Only the cache files cause conflicts which can be ignored

**Comment by PuneetGopinath** [comment]
Why? GitHub docs itself says to remove it and and node_modules to .gitignore

**Comment by abhijoshi2k** [comment]
Idk why, but I don't see any conflicts on local. Should I merge this into `updation-time` then?

**Comment by Andre601** [comment]
Conflicts seem resolved. Just the action was failing for some reason, but I leave this up to you to figure out

**Comment by PuneetGopinath** [comment]
They fail because there is nothing to commit, or no changes happen to the files when you run `npm run build` and `npm run format`.

**Pull request merged**
