### PR TITLE
added feature to ignore repos

### LINKED ISSUE #223: Feature request: Ignoring repos
### Checks

- [X] I [searched the issues page](https://github.com/Readme-Workflows/recent-activity/issues?q=is%3Aissue) for already existing feature requests.

### Description

I have some upptime instances on some Github repos and on the readme it keeps popping up the commits made by the bot. Is there any way to ignore those repos and show only the "real" commits?

### Alternatives considered

_No response_

### PR DESCRIPTION
**Pull request by adityajoshi12**
Signed-off-by: Aditya Joshi <adityaprakashjoshi1@gmail.com>

## Checks

I have...

- [x] read and understood the [Contributing Guidelines][contributing]
- [ ] Updated any nessecary files such as the README.md and/or CHANGELOG.md.

## Type of Pull request

- [x] **Minor Change**  
  This Pull request doesn't break existing configuration.
- [ ] **Major Change**  
  This Pull request will break existing configuration.
- [ ] **Bug fix**  
  This Pull request will fix a (critical) bug.
- [ ] **Documentation**  
  This Pull request only changes documentation (README.md, CHANGELOG.md, etc.)
- [ ] **Other:** `__________` 

## Description

This PR contains the changeset for ignoring the events for repos defined in the configuration file. The repos that needs to be ignored can be defined as following In the configuration file.
```
settings:
  username: "Readme-Workflows"
  commit_msg: "⚡ Update README with the recent activity"
  max_lines: 5
  ...
  ignored_repos:
    - username/repo
   ...
```

Closes #223 

[contributing]: https://github.com/Readme-Workflows/.github/blob/main/.github/CONTRIBUTING.md

### CODE REVIEW

**Comment by abhijoshi2k** [comment]
Hi @adityajoshi12 
The feature doesn't work on my repo. Please check again.
[Workflow file](https://github.com/abhijoshi2k/abhijoshi2k/blob/master/.github/workflows/update-readme.yml)
[Config file](https://github.com/abhijoshi2k/abhijoshi2k/blob/master/.github/update-readme.config.yml)

**Comment by adityajoshi12** [comment]
> Hi @adityajoshi12 The feature doesn't work on my repo. Please check again. [Workflow file](https://github.com/abhijoshi2k/abhijoshi2k/blob/master/.github/workflows/update-readme.yml) [Config file](https://github.com/abhijoshi2k/abhijoshi2k/blob/master/.github/update-readme.config.yml)
> 
> Try `npm run build` and then push.
added the updated `dist/index.js`

**Comment by abhijoshi2k** [comment]
It is working now.
@adityajoshi12 is this ready to merge?

**Review by abhijoshi2k — APPROVED** [review]

**Comment by adityajoshi12** [comment]
> It is working now.
> @adityajoshi12 is this ready to merge?

Sure, please go ahead.

**Pull request merged**
