### PR TITLE
Use src folder

### PR DESCRIPTION
**Pull request by PuneetGopinath**
## Checks

I have...

- [x] read and understood the [Contributing Guidelines][contributing]
- [ ] Updated any nessecary files such as the README.md and/or CHANGELOG.md.

## Type of Pull request

- [x] **Minor Change**  
  This Pull request doesn't break existing configuration.
- [ ] **Major Change**  
  This Pull request will break existing configuration.
- [ ] **Bug fix**  
  This Pull request will fix a (critical) bug.
- [ ] **Documentation**  
  This Pull request only changes documentation (README.md, CHANGELOG.md, etc.)
- [ ] **Other:** `__________` 

## Description

Move all source files a new folder `src`

Closes #

[contributing]: https://github.com/Readme-Workflows/recent-activity/blob/main/.github/CONTRIBUTING.md

### CODE REVIEW

**Comment by abhijoshi2k** [comment]
Build was not run after last commit. Is there an issue in workflow? @PuneetGopinath

**Comment by PuneetGopinath** [comment]
> Build was not run after last commit. Is there an issue in workflow? @PuneetGopinath

No issues

**Comment by abhijoshi2k** [comment]
> No issues

It should have run according to me

**Comment by PuneetGopinath** [comment]
> It should have run according to me

How?

**Comment by abhijoshi2k** [comment]
> > It should have run according to me
> 
> How?

```
on:
  push:
    paths:
      - "**.js"
      - "**.json"
  workflow_dispatch:
```
This is the trigger for the workflow

**Comment by PuneetGopinath** [comment]
> This is the trigger for the workflow. `package.json` was updated.

I don't know what happened but I ran it manually

**Comment by abhijoshi2k** [comment]
I think this PR is ready for review.

**Review by abhijoshi2k — APPROVED** [review]

**Comment by PuneetGopinath** [comment]
> I don't know what happened but I ran it manually

But still it didn't commit, if you want you can run it.

**Comment by abhijoshi2k** [comment]
The workflow has now triggered.

**Comment by abhijoshi2k** [comment]
@PuneetGopinath can we merge?

**Pull request merged**
