### PR TITLE
Prepare Changelog for v1.4.0

### PR DESCRIPTION
**Pull request by Andre601**
Thank you for contributing! Please check the following things before submiting your PR:

Required:
- [x] I have read and followed the [contributing guidelines](https://github.com/Readme-Workflows/recent-activity/blob/main/.github/CONTRIBUTING.md)

If necessary:
- [ ] I have updated the README and documentation.
- [x] I have updated the ChangeLog with the changes I have made.

## Description

Update Changelog for v1.4.0

Closes #

---------------------------------------------------------------------

**Note:** we will close your PR without comment if you do not check the required boxes above and provide ALL requested information.

### CODE REVIEW

**Comment by PuneetGopinath** [comment]
@Andre601 Isn't this ready for review

**Comment by PuneetGopinath** [comment]
I no need to review this pr

**Comment by abhijoshi2k** [comment]
> I think no need to review this pr

I didn't get you

**Comment by PuneetGopinath** [comment]
I meant we can merge it?

**Review by abhijoshi2k — APPROVED** [review]
We can merge this

**Pull request merged**
