### PR TITLE
Prepare Changelog for 1.2.2

### PR DESCRIPTION
**Pull request by Andre601**
Thank you for contributing! Please check the following things before submiting your PR:

Required:
- [x] I have read and followed the [contributing guidelines](https://github.com/Readme-Workflows/recent-activity/blob/main/.github/CONTRIBUTING.md)

If necessary:
- [ ] I have updated the README and documentation.
- [x] I have updated the ChangeLog with the changes I have made.

> Will be merged once 1.2.2 has been released. Hopefully I won't forget to set the release data this time...

Closes #

---------------------------------------------------------------------

**Note:** we will close your PR without comment if you do not check the required boxes above and provide ALL requested information.

### CODE REVIEW

**Comment by Andre601** [comment]
....Thanks for merging this without even asking if it is ready. Jesus man, show patience and ASK first, because as it was mentioned in the comment will I need to update the Release date first.

**Comment by abhijoshi2k** [comment]
I'm so sorry I misread it I guess. I must have asked you. Shouldn't have hurried so much.
Bro, this won't be happening again.
I'll revert the commit.
Sorry again!

**Comment by Andre601** [comment]
No need to revert now. What's done is done.

**Comment by abhijoshi2k** [comment]
> No need to revert now. What's done is done.

I just wanna say I'm sorry for hurrying.
I hope there are no hard feelings

**Comment by Andre601** [comment]
It's fine.
But I think we should set a rule that a PR is only mergable if the author gave his OK to it... Or maybe always keep them as drafts until they are ready to then turn into ready.

**Comment by abhijoshi2k** [comment]
> It's fine.
> But I think we should set a rule that a PR is only mergeable if the author gave his OK to it... Or maybe always keep them as drafts until they are ready to then turn into ready.

Yeah. You are right. We'll apply both of those rules next time onwards.

**Pull request merged**
