### PR TITLE
Added URL_FORMAT parameter

### PR DESCRIPTION
**Pull request by abhijoshi2k**
Thank you for contributing! Please check the following things before submiting your PR:

Required:
- [x] I have read and followed the [contributing guidelines](https://github.com/Readme-Workflows/recent-activity/blob/main/.github/CONTRIBUTING.md)

If necessary:
- [ ] I have updated the README and documentation.
- [ ] I have updated the ChangeLog with the changes I have made.

Added parameter to customize output of events.

---------------------------------------------------------------------

**Note:** we will close your PR without comment if you do not check the required boxes above and provide ALL requested information.

### CODE REVIEW

**Comment by abhijoshi2k** [comment]
@Andre601 @PuneetGopinath Can you please test and review?

**Comment by PuneetGopinath** [comment]
> @Andre601 @PuneetGopinath Can you please test and review?

Yes, plz wait

**Comment by Andre601** [comment]
Doesn't look like it works?

image
image

**Comment by abhijoshi2k** [comment]
> Doesn't look like it works?
> 
> image
> image

I forgot to run build. Please try now

**Comment by Andre601** [comment]
Seems to do the job.
image

**Comment by PuneetGopinath** [comment]
> Seems to do the job.
> image

Yes, it works after running build

**Review by Andre601 — APPROVED** [review]

**Review by PuneetGopinath — APPROVED** [review]

**Comment by abhijoshi2k** [comment]
@PuneetGopinath can you update changelog on same branch.
And
@Andre601 can you update readme for the same on this branch?
Then we will merge this and the other pr and release

**Comment by PuneetGopinath** [comment]
> @PuneetGopinath can you update changelog on same branch.
> And
> @Andre601 can you update readme for the same on this branch?
> Then we will merge this pr and release

No need to update changelog, as this pr updates #11

**Comment by Andre601** [comment]
One thing tho... `URL_FORMAT` sounds misleading as all this does is essentially changing the text in the embedded link.
So why not call it `URL_TEXT` instead?

**Comment by abhijoshi2k** [comment]
> One thing tho... `URL_FORMAT` sounds misleading as all this does is essentially changing the text in the embedded link.
> So why not call it `URL_TEXT` instead?

Sounds right. I'll make the changes and push.

**Comment by abhijoshi2k** [comment]
> > @PuneetGopinath can you update changelog on same branch.
> > And
> > @Andre601 can you update readme for the same on this branch?
> > Then we will merge this pr and release
> 
> No need to update changelog, as this pr updates #11

Okay

**Comment by abhijoshi2k** [comment]
@Andre601 we will merge after you update readme.
Do it on this branch itself.

**Comment by PuneetGopinath** [comment]
> This looks good @Andre601 .
> I think this is ready to be merged. What do you think? @PuneetGopinath

Looks good

**Comment by abhijoshi2k** [comment]
> > This looks good @Andre601 .
> > I think this is ready to be merged. What do you think? @PuneetGopinath
> 
> Looks good

Alright. I'll merge

**Comment by abhijoshi2k** [comment]
@PuneetGopinath @Andre601 Should I release this?

**Pull request merged**
