### PR TITLE
Use config file

### LINKED ISSUE #52: Feature request: Keep the configuration in a file
Please check these things before submitting your issue:

- [x] I searched for duplicate or closed feature request [here](https://github.com/PuneetGopinath/github-activity-readme/issues?q=is%3Aissue)

**Is your feature request related to a problem? Please describe.**
N/A.

**Describe the solution you'd like**
I think you should keep the configuration in a separate file (maybe a file like `.github/recent-activity-config.yml`) as there are too many inputs and only add `config_file` as a option in github action inputs which will tell path to the configuration file. I will assign this to my self if you agree with this request and plz help me in the process of doing it.

**Describe alternatives you've considered**
N/A.

**Additional context**
Probaly I will use [js-yaml](https://www.npmjs.com/package/js-yaml) as a dependency to do parse the yaml config.

### PR DESCRIPTION
**Pull request by PuneetGopinath**
## Checks

I have...

- [x] read and understood the [Contributing Guidelines][contributing]
- [x] Updated any nessecary files such as the README.md and/or CHANGELOG.md.

## Type of Pull request

- [ ] **Minor Change**  
  This Pull request doesn't break existing configuration.
- [x] **Major Change**  
  This Pull request will break existing configuration.
- [ ] **Bug fix**  
  This Pull request will fix a (critical) bug.
- [ ] **Documentation**  
  This Pull request only changes documentation (README.md, CHANGELOG.md, etc.)
- [ ] **Other:** `__________` 

## Description

See #52 for the details, etc.

Closes #52

[contributing]: https://github.com/Readme-Workflows/recent-activity/blob/main/.github/CONTRIBUTING.md

### CODE REVIEW

**Comment by abhijoshi2k** [comment]
@PuneetGopinath FYI, `TIMEZONE_OFFSET` is going to be renamed with `TIMEZONE`
You do not need to change it in any of the current file as I'll do it on other branch and then merge. You just have to take care of it in new YAML

**Comment by abhijoshi2k** [comment]
@PuneetGopinath please run `npm i` on your side and commit the new `package-lock.json` to run build successfully

**Comment by PuneetGopinath** [comment]
> @PuneetGopinath please run `npm i` on your side and commit the new `package-lock.json` to run build successfully

That's what I asked you in #52, now I will do it.

**Comment by PuneetGopinath** [comment]
@abhijoshi2k Can you check the commit "Fix index.js", that whether it will work or not?

**Comment by PuneetGopinath** [comment]
@abhijoshi2k Why is prettier checking `dist/index.js`, I think you added it to the `.prettierignore`

**Comment by abhijoshi2k** [comment]
> @abhijoshi2k Can you check the commit "Fix index.js", that whether it will work or not?

No. that won't work.
You don't need to make any changes to any file other than `config.js` and `parseYaml.js`
`config.js` should export exact same values as it was exporting before

**Comment by abhijoshi2k** [comment]
Try using spread operator again while exporting. f.e. `...conf`

**Comment by PuneetGopinath** [comment]
> @abhijoshi2k Why is prettier checking `dist/index.js`, I think you added it to the `.prettierignore`

@abhijoshi2k

**Comment by abhijoshi2k** [comment]
> > @abhijoshi2k Why is prettier checking `dist/index.js`, I think you added it to the `.prettierignore`
> 
> @abhijoshi2k
> EDIT: See https://github.com/Readme-Workflows/recent-activity/pull/53/checks?check_run_id=2645996290

It's programmed to format all files ending with `.js`. That might be the reason

**Comment by PuneetGopinath** [comment]
> It's programmed to format all files ending with `.js`. That might be the reason

Can you fix that?

**Comment by abhijoshi2k** [comment]
> > It's programmed to format all files ending with `.js`. That might be the reason
> 
> Can you fix that?

I tried. But couldn't. That's fine. It won't cause any issue.

**Comment by abhijoshi2k** [comment]
@PuneetGopinath I feel there's a better way to structure `config.js`. Would you like me to make a commit?

**Comment by PuneetGopinath** [comment]
> @PuneetGopinath I feel there's a better way to structure `config.js`. Would you like me to make a commit?

Sure, that's what I said in #52
```
I will assign this to my self if you agree with this request and plz help me in the process of doing it.
```

**Comment by PuneetGopinath** [comment]
@abhijoshi2k I am receiving too many emails for this failing workflow, can we remove it to run on PRs.

**Comment by PuneetGopinath** [comment]
@abhijoshi2k You shouldn't use those vars as we are going to remove them in config.js and action.yml

**Comment by abhijoshi2k** [comment]
> @abhijoshi2k You shouldn't use those vars as we are going to remove them in config.js and action.yml

Let's not remove them. It'll automatically take default value and then replace it as per user's YML file

**Comment by abhijoshi2k** [comment]
> @abhijoshi2k I am receiving too many emails for this failing workflow, can we remove it to run on PRs.

It's working on local though. IDK what's the issue here

**Comment by PuneetGopinath** [comment]
> > @abhijoshi2k You shouldn't use those vars as we are going to remove them in config.js and action.yml
> 
> Let's not remove them. It'll automatically take default value and then replace it as per user's YML file.
> Users will have a choice between using same yml or separate one

That wouldn't be nice, the request was itself for removing and adding the config file instead.

**Comment by PuneetGopinath** [comment]
> > @abhijoshi2k I am receiving too many emails for this failing workflow, can we remove it to run on PRs.
> 
> It's working on local though. IDK what's the issue here

The issue is **I am receiving too many emails**

**Comment by abhijoshi2k** [comment]
> > > @abhijoshi2k I am receiving too many emails for this failing workflow, can we remove it to run on PRs.
> > 
> > 
> > It's working on local though. IDK what's the issue here
> 
> The issue is **I am receiving too many emails**

Okay disable it

**Comment by PuneetGopinath** [comment]
> > Let's not remove them. It'll automatically take default value and then replace it as per user's YML file.
> > Users will have a choice between using same yml or separate one
> 
> That wouldn't be nice, the request was itself for removing and adding the config file instead.

@abhijoshi2k I already removed them also

**Comment by abhijoshi2k** [comment]
The keys of each and every input from separate yml file will have to be same as the ones in `config.js`. Else it won't overwrite.

**Comment by PuneetGopinath** [comment]
@abhijoshi2k Sorry, but I removed those inputs in action.yml and config.js, can you say me why you want them

**Comment by abhijoshi2k** [comment]
The disable events input needs to be formatted into list before adding it to object. Make sure its done

**Comment by PuneetGopinath** [comment]
@abhijoshi2k I have some work now, I will continue tomorrow

**Comment by abhijoshi2k** [comment]
@PuneetGopinath workflow is now working

**Comment by PuneetGopinath** [comment]
Thanks for converting them to lowercase

**Comment by abhijoshi2k** [comment]
Looks like there are going to be a lot of conflicts while merging this pr.

**Comment by PuneetGopinath** [comment]
> Looks like there are going to be a lot of conflicts while merging this pr.

Yes, I will resolve them.

**Comment by abhijoshi2k** [comment]
> Yes, I will resolve them.
I shall resolve them once #54 is merged.
We'll have to be careful with the timezone code as its variables aren't in lowercase yet

**Comment by abhijoshi2k** [comment]
@PuneetGopinath I think functional changes are done here.

**Comment by abhijoshi2k** [comment]
@Andre601 All the functional changes are done.
Refer `sample.yml` for structure of config file. Also refer `action.yml` for new input formats.
Kindly update changelog, wikis and readme whenever possible.
Also let me know if you find any bug or non-conventional approach.

**Comment by Andre601** [comment]
> @Andre601 All the functional changes are done.
> Refer `sample.yml` for structure of config file. Also refer `action.yml` for new input formats.
> Kindly update changelog, wikis and readme whenever possible.
> Also let me know if you find any bug or non-conventional approach.

The `username: core.getInput("GH_USERNAME")` feels kinda out of place, especially for a new user starting with this.
Why not use some placeholder variable like `{OWNER}` or similar that the Action would then see as getting the `core.getInput("GH_USERNAME")`?

**Comment by Andre601** [comment]
Also, are all the options optional or will the user require to set them all, even if they're the default?

**Comment by abhijoshi2k** [comment]
> The `username: core.getInput("GH_USERNAME")` feels kinda out of place, especially for a new user starting with this.
> Why not use some placeholder variable like `{OWNER}` or similar that the Action would then see as getting the `core.getInput("GH_USERNAME")`?

It does have a default value of user's own username. So there's no need for the user to add `GH_USERNAME` input.
I shall edit the sample.yml file and make it more relevant.

**Comment by abhijoshi2k** [comment]
> Also, are all the options optional or will the user require to set them all, even if they're the default?

None of the options are required. If they are not specified, default will be used

**Comment by Andre601** [comment]
> > Also, are all the options optional or will the user require to set them all, even if they're the default?
> 
> None of the options are required. If they are not specified, default will be used

Good.
Do you also account for special cases such as providing empty Strings or just spaces or similar?

**Comment by Andre601** [comment]
The `review_approved` option should be renamed to `changes_approved` to match the `changes_requested` option and also make more sense since you don't approve a review. 🤣

**Comment by PuneetGopinath** [comment]
> Good.
> Do you also account for special cases such as providing empty Strings or just spaces or similar?

No, providing "empty strings or just spaces" won't be changed to the default string!! You can comment out options if you want there default option
Example, I believe the code is easy to understand for you @Andre601.
```
let job = {
    jobTitle: 'JavaScript Developer',
    country: 'USA'
};

let location = {
    city: 'London',
    country: 'England'
};

let remoteJob = {
    ...job,
    ...location
};

console.log(remoteJob);
```
Output:
```
{
    jobTitle: 'JavaScript Developer',
    country: 'England',
    city: 'London'
}
```

This method is the way we currently merge the configuration file and default settings.
If you didn't still understand the code, I can explain you a bit more.
The code above creates a object,

**Comment by PuneetGopinath** [comment]
Sorry, but I don't know why I immediately clicked the close with comment option.

**Comment by PuneetGopinath** [comment]
@abhijoshi2k @Andre601 Can you check the updated wiki?

**Comment by abhijoshi2k** [comment]
> @abhijoshi2k @Andre601 Can you check the updated wiki?

I think the inputs should be shown on top. Also, link to `sample.yml` is incorrect.

**Comment by abhijoshi2k** [comment]
> > @abhijoshi2k @Andre601 Can you check the updated wiki?
> 
> I think the inputs should be shown on top. Also, link to `sample.yml` is incorrect.

Also, I have updated the `disabled_events` in `sample.yml`. You will need to update that in wiki

**Comment by PuneetGopinath** [comment]
> > @abhijoshi2k @Andre601 Can you check the updated wiki?
> 
> I think the inputs should be shown on top. Also, link to `sample.yml` is incorrect.

The link will return a 404 as the file is not in branch main

**Comment by PuneetGopinath** [comment]
@Andre601 Sorry for updating the wiki, I rebased and force pushed so my commit is droped.
Can you add the Inputs sections and what @abhijoshi2k requested?
The inputs section can be something like this:
```


## Inputs

These are the inputs you can supply through github actions (that you can set through the `with` option in a workflow file)

<table>
  <thead>
    <tr>
      <th>Option</th>
      <th>Description</th>
      <th>Default</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><code>GH_USERNAME</code></td>
      <td>The User to get latest activity from</td>
      <td><i>Repository Owner</i></td>
    </tr>
    <tr>
      <td><code>CONFIG_FILE</code></td>
      <td>The location of the configuration file, remember to add `./` before the path to the file.</td>
      <td><i>./.github/recent-activity.config.yml</i></td>
    </tr>
  </tbody>
</table>
```

**Comment by abhijoshi2k** [comment]
> > > @abhijoshi2k @Andre601 Can you check the updated wiki?
> > 
> > 
> > I think the inputs should be shown on top. Also, link to `sample.yml` is incorrect.
> 
> The link will return a 404 as the file is not in branch main

Okay.

**Comment by Andre601** [comment]
The link to the sample.yml doesn't work because the file has yet to be added to the main branch.

**Comment by PuneetGopinath** [comment]
> The link to the sample.yml doesn't work because the file has yet to be added to the main branch.

I said that.

**Comment by Andre601** [comment]
> Also, I have updated the `disabled_events` in `sample.yml`. You will need to update that in wiki
> `review_approved` is changed to `changes_approved`.
> You need to mention that all of the options are optional.
> 
> Instead of giving link to `sample.yml`, I think we should simply provide the contents of the file on wiki.

Updated the wiki.
Also, I intentionally link to the file instead of having a copy of it on the wiki. Reason for that is, that in case of the file changing, we don't have to update the wiki as much...

**Comment by abhijoshi2k** [comment]
The home and example wiki also need to be updated right? @Andre601

**Comment by PuneetGopinath** [comment]
> The home and example wiki also need to be updated right? @Andre601

@Andre601

**Comment by Andre601** [comment]
image

**Comment by PuneetGopinath** [comment]
@Andre601 Can I add a footer in wiki?

**Comment by Andre601** [comment]
> @Andre601 Can I add a footer in wiki?

Go ahead.

**Comment by PuneetGopinath** [comment]
> > @Andre601 Can I add a footer in wiki?
> 
> Go ahead.

Check it out now.

**Comment by PuneetGopinath** [comment]
We have to resolve conflicts

**Review by Andre601 — APPROVED** [review]

**Review by abhijoshi2k — APPROVED** [review]

**Comment by abhijoshi2k** [comment]
> We have to resolve conflicts

Will do it

**Pull request merged**
