### PR TITLE
Issue 4 - Option to disable specific activity types from being shown in the activity list

### LINKED ISSUE #4: Feature request: Option to disable specific activity types from being shown in the activity list
Please check these things before submitting your issue:

- [x] I searched for duplicate or closed feature request [here](https://github.com/PuneetGopinath/github-activity-readme/issues?q=is%3Aissue)

**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Please see https://github.com/PuneetGopinath/github-activity-readme/issues/8 for full context and info.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by PuneetGopinath**
Thank you for contributing! Please check the following things before submiting your PR:

Required:
- [x] I have read and followed the [contributing guidelines](https://github.com/Readme-Workflows/recent-activity/blob/main/.github/CONTRIBUTING.md)

If necessary:
- [ ] I have updated the ChangeLog with the changes I have made.
- [ ] I have updated the README and documentation.

> Closes #4

Closes #4

---------------------------------------------------------------------

**Note:** we will close your PR without comment if you do not check the required boxes above and provide ALL requested information.

### CODE REVIEW

**Comment by PuneetGopinath** [comment]
@abhijoshi2k Plz review

**Review by abhijoshi2k — CHANGES_REQUESTED** [review]
Don't put questions in description. Change those to descriptive statements.
Questions do not look good I feel.

**Comment by PuneetGopinath** [comment]
> Don't put questions in description. Change those to descriptive statements.
> Questions do not look good I feel.

Oh, will change

**Comment by PuneetGopinath** [comment]
I am getting error `Error: Invalid status code: 1 --  `

**Comment by abhijoshi2k** [comment]
I think you have put conditions on wrong region.
They should be put when filter function is used.

**Comment by PuneetGopinath** [comment]
> I think you have put conditions on wrong region.
> They should be put when filter function is used.

Ok, will check

**Comment by PuneetGopinath** [comment]
Can you help me

**Comment by abhijoshi2k** [comment]
> Can you help me

Yeah. You want me to take over this branch?

**Comment by abhijoshi2k** [comment]
I think your current code should also work

**Comment by abhijoshi2k** [comment]
I found the issue bro.
Issue was that the values are not boolean. They are considered string.

**Review by abhijoshi2k — APPROVED** [review]

**Comment by PuneetGopinath** [comment]
> I found the issue bro.
> Issue was that the values are not boolean. They are considered string.

Oh, Thanks

**Pull request merged**
