### PR TITLE
Add whitelist feature

### LINKED ISSUE #76: Feature request: I would like a whitelist option which is just opposite to the disabled_events option
Please check these things before submitting your issue:

- [x] I searched for duplicate or closed feature request [here](https://github.com/Readme-Workflows/recent-activity/issues?q=is%3Aissue)

**Is your feature request related to a problem? Please describe.**
N/A.

**Describe the solution you'd like**
If there was a way to add the only events we need, it would be useful when our users wanna select 1 or 2 events. They would need to add a big disabled_events list instead of a small whitelist option

**Describe alternatives you've considered**
N/A.

**Additional context**
N/A.

### PR DESCRIPTION
**Pull request by abhijoshi2k**
## Checks

I have...

- [x] read and understood the [Contributing Guidelines][contributing]
- [ ] Updated any nessecary files such as the README.md and/or CHANGELOG.md.

## Type of Pull request

- [x] **Minor Change**  
  This Pull request doesn't break existing configuration.
- [ ] **Major Change**  
  This Pull request will break existing configuration.
- [ ] **Bug fix**  
  This Pull request will fix a (critical) bug.
- [ ] **Documentation**  
  This Pull request only changes documentation (README.md, CHANGELOG.md, etc.)
- [ ] **Other:** `__________` 

## Description
Added event whitelisting. Using `whitelisted_events` as parameter in config files will allow only those events to be included in recent-activity.

### Note:
`whitelisted_events` will have priority over `disabled_events`

Closes #76 

[contributing]: https://github.com/Readme-Workflows/recent-activity/blob/main/.github/CONTRIBUTING.md

### CODE REVIEW

**Comment by abhijoshi2k** [comment]
> Seriously, I didn't thought you will work now itself no this.

It was very small change. Didn't take much time.

**Comment by abhijoshi2k** [comment]
@PuneetGopinath Can you check if it's working as expected? Then I'll mention Andreas to update documentation and/or changelog.

**Comment by PuneetGopinath** [comment]
An error occurred: https://github.com/PuneetGopinath/activity-test/runs/2970299783?check_suite_focus=true 🔥

**Comment by PuneetGopinath** [comment]
@abhijoshi2k

**Comment by abhijoshi2k** [comment]
> An error occurred: https://github.com/PuneetGopinath/activity-test/runs/2970299783?check_suite_focus=true

Our workflow does not support triggering on `push` event. It requires `cron` schedule or `workflow_dispatch` trigger. Please remove `push` trigger.

**Comment by PuneetGopinath** [comment]
> > An error occurred: https://github.com/PuneetGopinath/activity-test/runs/2970299783?check_suite_focus=true
> 
> Our workflow does not support triggering on `push` event. It requires `cron` schedule or `workflow_dispatch` trigger. Please remove `push` trigger.

I know that, am not a fool. I mean that when even I didn't add any push event it says that it is not supported

**Comment by PuneetGopinath** [comment]
Check the config file for yourself

**Comment by abhijoshi2k** [comment]
> Check the config file for yourself

Dude you have a push trigger in workflow file. You need to remove it!

**Comment by PuneetGopinath** [comment]
> > Check the config file for yourself
> 
> Dude you have a push trigger in workflow file. You need to remove it!

Hmm, okay
I just now changed it. But didn't thought that push event would make a problem, as the same push event is in recent-activity

**Comment by abhijoshi2k** [comment]
@PuneetGopinath it's working.
https://github.com/PuneetGopinath/activity-test/runs/2970474661?check_suite_focus=true

**Comment by PuneetGopinath** [comment]
> @PuneetGopinath it's working.
> https://github.com/PuneetGopinath/activity-test/runs/2970474661?check_suite_focus=true

I saw, you changed it.

**Comment by abhijoshi2k** [comment]
@Andre601 Can you update the readme and changelog?

**Comment by PuneetGopinath** [comment]
Also add the note: `whitelisted_events` will have priority over `disabled_events`

**Comment by Andre601** [comment]
> @Andre601 Can you update the readme and changelog?

I will once this PR is merged

**Comment by abhijoshi2k** [comment]
> > @Andre601 Can you update the readme and changelog?
> 
> I will once this PR is merged

Okay. I'll add `Status: Ready` label. @PuneetGopinath you can review and merge.

**Comment by PuneetGopinath** [comment]
@Andre601 You can update docs (or wiki)
Also add the note: whitelisted_events will have priority over disabled_events

**Pull request merged**
