### PR TITLE
Update run-build.yml

### PR DESCRIPTION
**Pull request by PuneetGopinath**
Thank you for contributing! Please check the following things before submiting your PR:

Required:
- [x] I have read and followed the [contributing guidelines](https://github.com/Readme-Workflows/recent-activity/blob/main/.github/CONTRIBUTING.md)

If necessary:
- [ ] I have updated the README and documentation.
- [ ] I have updated the ChangeLog with the changes I have made.

> update run-build.yml

Closes #

---------------------------------------------------------------------

**Note:** we will close your PR without comment if you do not check the required boxes above and provide ALL requested information.

### CODE REVIEW

**Review by Andre601 — APPROVED** [review]

**Comment by Andre601** [comment]
Just as a heads up: You don't need my review for future PRs if it is affecting JS and/or npm, because I have 0 knowledge about this stuff. 😆

**Comment by abhijoshi2k** [comment]
I don't understand why is the check failing?

**Comment by Andre601** [comment]
> I don't understand why is the check failing?

```
[warn] index.js
[warn] Code style issues found in the above file(s). Forgot to run Prettier?
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! activity-readme@1.2.1 format:check: `prettier --check index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the activity-readme@1.2.1 format:check script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by Andre601** [comment]
Also, why is it 1.2.1?

**Comment by abhijoshi2k** [comment]
Prettier was not run after last update to index.js
I still don't understand why it's showing v1.2.1
Also, the workflow run-build did not run which would have fixed this issue.

**Comment by PuneetGopinath** [comment]
> I still don't understand why it's showing v1.2.1

I think my mistake

**Comment by abhijoshi2k** [comment]
@PuneetGopinath You removed name from the workflow. Wouldn't it cause issue?

**Comment by PuneetGopinath** [comment]
> @PuneetGopinath You removed name from the workflow. Wouldn't it cause issue?

I didn't remove any name instead I added one.

**Review by abhijoshi2k — APPROVED** [review]
Right. Is it ready to merge now?

**Comment by PuneetGopinath** [comment]
Yep

**Pull request merged**
