### PR TITLE
Switch to GitHub-integrated release creator

### PR DESCRIPTION
**Pull request by Andre601**
## Checks

I have...

- [x] read and understood the [Contributing Guidelines][contributing]
- [x] Updated any nessecary files such as the README.md and/or CHANGELOG.md.

## Type of Pull request

- [ ] **Minor Change**  
  This Pull request doesn't break existing configuration.
- [ ] **Major Change**  
  This Pull request will break existing configuration.
- [ ] **Bug fix**  
  This Pull request will fix a (critical) bug.
- [ ] **Documentation**  
  This Pull request only changes documentation (README.md, CHANGELOG.md, etc.)
- [x] **Other:** `Release system` 

## Description

GitHub released a public beta for the automatic release creation.

- Blog Post: https://github.blog/changelog/2021-10-04-improvements-to-github-releases-public-beta/
- Documentation: https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes

Downside of this is, that it will essentially require us to manually update stuff like the version of the release and similar...

Closes #

[contributing]: https://github.com/Readme-Workflows/.github/blob/main/.github/CONTRIBUTING.md

### CODE REVIEW

**Comment by PuneetGopinath** [comment]
Wow👏. Have you tested it?

**Comment by Andre601** [comment]
> Wow👏. Have you tested it?

Not sure how I could test it...

**Comment by PuneetGopinath** [comment]
> > Wow👏. Have you tested it?
> 
> Not sure how I could test it...

I mean have you seen it somewhere? Or tested in any of your repositories

**Comment by Andre601** [comment]
> I mean have you seen it somewhere? Or tested in any of your repositories

No. There is always a first time for everything and since that has been released literally yesterday would I doubt many have it already...

**Review by PuneetGopinath — APPROVED** [review]
LGTM

**Review by abhijoshi2k — APPROVED** [review]

**Pull request merged**
