### PR TITLE
Create PR Commenter

### PR DESCRIPTION
**Pull request by Andre601**
Thank you for contributing! Please check the following things before submiting your PR:

Required:
- [x] I have read and followed the [contributing guidelines](https://github.com/Readme-Workflows/recent-activity/blob/main/.github/CONTRIBUTING.md)

If necessary:
- [ ] I have updated the README and documentation.
- [ ] I have updated the ChangeLog with the changes I have made.

> Adds a Action that comments on Pull requests which have been labeled with specific labels.
> The goal here is to have an easy way to mark a PR as mergable by adding a special Label and the Action would then send a Message saying that the PR is now ready for merging.
> It could also get expanded to allow canned responses to specific labels for issues and/or PRs.

Closes #

---------------------------------------------------------------------

**Note:** we will close your PR without comment if you do not check the required boxes above and provide ALL requested information.

### CODE REVIEW

**Comment by PuneetGopinath** [comment]
I think you created for:
```
....Thanks for merging this without even asking if it is ready. Jesus man, show patience and ASK first, because as it was mentioned in the comment will I need to update the Release date first.
```

**Comment by Andre601** [comment]
More or less.
It's just another step to make sure that a PR is actually ready, because it could happen that you click "Ready for review" but then notice that something needs a change, but it would then be too late.

(It's also easier imo than typing a message that your PR is ready. I'm fucking lazy here :P)

**Comment by Andre601** [comment]
Ignore the failure. It can't find the label-commenter-config.yml because it isn't on the main branch yet.

**Comment by PuneetGopinath** [comment]
Ok, is it a GitHub app. Did you give access to our org.

**Comment by Andre601** [comment]
> Ok, is it a GitHub app. Did you give access to our org.

No. It's a GitHub Action. Not an app.

**Comment by PuneetGopinath** [comment]
Yep, I just forgot.

**Review by PuneetGopinath — APPROVED** [review]

**Comment by Andre601** [comment]
Here is an example of what it can do:
https://github.com/PlaceholderAPI/PlaceholderAPI/pull/628#issuecomment-839170062

But in summary it can do this:

- Comment on Pull requests and/or issue with canned responses
- Close or reopen a Pull request/Issue
- Lock a Pull request/Issue with an optional reason

What it does all depends on what you configured in the label-commenter-config.yml

More info: https://github.com/peaceiris/actions-label-commenter

**Comment by PuneetGopinath** [comment]
But I think the current config is not set for that, can you set that.

**Comment by Andre601** [comment]
> But I think the current config is not set for that, can you set that.

Not sure what you mean with that.

**Comment by PuneetGopinath** [comment]
> > But I think the current config is not set for that, can you set that.
> 
> Not sure what you mean with that.

I meant that the current configuration does not make the bot to comment when we are not following the contribution guidelines.

**Comment by Andre601** [comment]
> I meant that the current configuration does not make the bot to comment when we are not following the contribution guidelines. Can you set it

Added comments now for when Issues and PRs are (un)labeled with the "invalid" label.
Should the action also close issues/PRs and re-open them when they are labeled/unlabeled with invalid? Or would that be too aggressive?

**Comment by PuneetGopinath** [comment]
It would be better if it's closed when invalid

**Comment by Andre601** [comment]
> It would be better if it's closed when invalid

added that. Is it good now?

**Comment by PuneetGopinath** [comment]
Now it's cool, @abhijoshi2k plz review

**Comment by PuneetGopinath** [comment]
Can we also add
```
- name: duplicate
    labeled:
      issue:
        body: This issue already exists.
        action: close

**Comment by PuneetGopinath** [comment]
Waiting for @abhijoshi2k

**Review by abhijoshi2k — APPROVED** [review]
I liked this action. Looks good to go

**Pull request merged**
